!SUBROUTINE INTRWG(NACTIVE,NITER,INTIMAGE,XYZ,TURNONORDER,NCONOFF)
SUBROUTINE INTRWG(NACTIVE,INTIMAGE,XYZ,TURNONORDER,NCONOFF)
USE PORFUNCS
USE BOX_DERIVATIVES, ONLY: FRAC2CART, BOX2LAT, FRAC2CART
USE KEY,ONLY: ATOMACTIVE, NCONSTRAINT, CONACTIVE, NREPULSIVE, NNREPULSIVE, REPI, REPJ, REPCUT, NREPCUT, &
  &           NREPMAX, NREPI, NREPJ, INTFROZEN, CONOFFLIST,CONOFFTRIED, KINT, INTCONSTRAINTREP, USEFRACT, &
  &           BOXSTART, BOXFIN, BOX_PARAMS
USE COMMONS, ONLY: NATOMS, DEBUG, ZSYM
IMPLICIT NONE
INTEGER NCONOFF
CHARACTER(LEN=10) :: XYZFILE   = 'int.xyz   '
CHARACTER(LEN=10) :: QCIFILE   = 'QCIdump   '
INTEGER,INTENT(IN) :: TURNONORDER(NATOMS)!, NITER
INTEGER :: J2,INTIMAGE,J3,NACTIVE,LUNIT,GETUNIT
CHARACTER(LEN=80) :: FILENAME !,DUMMYS
DOUBLE PRECISION XYZ((3*NATOMS)*(INTIMAGE+2)), LOCALCELL(9)
DOUBLE PRECISION XYZFRAME(3*NATOMS), XYZTEMP(3*NATOMS)

FILENAME=XYZFILE

LUNIT=GETUNIT()
OPEN(UNIT=LUNIT,FILE=TRIM(ADJUSTL(FILENAME)),STATUS='replace')
DO J2=1,INTIMAGE+2
   XYZFRAME(1:3*NATOMS)=XYZ((J2-1)*3*NATOMS+1:J2*3*NATOMS)
   IF (.NOT.USEFRACT) THEN
      WRITE(LUNIT,'(i4/)') NATOMS
   ELSE
      WRITE(LUNIT,'(i8)') NATOMS
      BOX_PARAMS(1:6)=BOXSTART(1:6)+(BOXFIN(1:6)-BOXSTART(1:6))*(J2-1)/(INTIMAGE+1)
      CALL BOX2LAT(LOCALCELL)
      WRITE(LUNIT,'(A,9G20.10)') 'Lattice="',LOCALCELL(1:9)
      CALL FRAC2CART(XYZTEMP,XYZFRAME)
      XYZFRAME(1:3*NATOMS)=XYZTEMP(1:3*NATOMS)
   ENDIF
   DO J3=1,NATOMS
      IF (ATOMACTIVE(J3)) THEN
         WRITE(LUNIT,'(A5,1X,3F20.10)') ZSYM(J3),XYZFRAME(3*(J3-1)+1),XYZFRAME(3*(J3-1)+2), XYZFRAME(3*(J3-1)+3)  
      ELSE
         WRITE(LUNIT,'(A5,1X,3F20.10)') 'DU   ',XYZFRAME(3*(J3-1)+1),XYZFRAME(3*(J3-1)+2), XYZFRAME(3*(J3-1)+3)
      ENDIF
   ENDDO
ENDDO

WRITE(*,'(A,L5)') ' intrwg> USEFRACT=',USEFRACT
WRITE(*,'(A)') ' intrwg> Interpolated image coordinates were saved to xyz file "'//TRIM(FILENAME)//'"'

CLOSE(LUNIT)

!!!!!!!!!!!!!!!!!!!!!!!! DJW DEBUG ! comment next line if QCIdump is required
RETURN ! DJW the QCIdump file is big and we are not using it.

FILENAME=QCIFILE
LUNIT=GETUNIT()
OPEN(UNIT=LUNIT,FILE=TRIM(ADJUSTL(FILENAME)),STATUS='replace')

IF (DEBUG) WRITE(*,'(A,I10,A)') ' intlbfgs> dumping state for ',NACTIVE,' active atoms'
WRITE(LUNIT,'(I10)') NACTIVE
! IF (DEBUG)   WRITE(*,'(A,I10,A)') ' intlbfgs> dumping spring constant and repulsive prefactor'
WRITE(LUNIT,'(2G20.10)') KINT, INTCONSTRAINTREP
! WRITE(*,'(A,I10,A)') ' intlbfgs> dumping turnonorder for ',NACTIVE,' active atoms'
WRITE(LUNIT,'(12I8)') TURNONORDER(1:NACTIVE)
! WRITE(*,'(A)') ' intlbfgs> dumping atomactive'
WRITE(LUNIT,'(12L5)') ATOMACTIVE(1:NATOMS)
WRITE(LUNIT,'(I10)') NCONSTRAINT
! WRITE(*,'(A,I10,A)') ' intlbfgs> dumping conactive for ',NCONSTRAINT,' constraints'
WRITE(LUNIT,'(12L5)') CONACTIVE(1:NCONSTRAINT)

WRITE(LUNIT,'(3I12,G20.10)') NREPULSIVE,NNREPULSIVE,NREPMAX
! WRITE(*,'(A,3I10,G20.10)') ' intlbfgs> dumping NREPULSIVE,NNREPULSIVE,NREPMAX=',NREPULSIVE,NNREPULSIVE,NREPMAX

WRITE(LUNIT,'(12I8)') REPI(1:NREPULSIVE)
! WRITE(*,'(A)') ' intlbfgs> dumped REPI:'
WRITE(LUNIT,'(12I8)') REPJ(1:NREPULSIVE)
! WRITE(*,'(A)') ' intlbfgs> dumped REPJ:'
WRITE(LUNIT,'(12I8)') NREPI(1:NNREPULSIVE)
! WRITE(*,'(A)') ' intlbfgs> dumped NREPI:'
WRITE(LUNIT,'(12I8)') NREPJ(1:NNREPULSIVE)
! WRITE(*,'(A)') ' intlbfgs> dumped NREPJ:'

WRITE(LUNIT,'(6G20.10)') REPCUT(1:NREPULSIVE)
! WRITE(*,'(A)') ' intlbfgs> dumped REPCUT:'
WRITE(LUNIT,'(6G20.10)') NREPCUT(1:NNREPULSIVE)
! WRITE(*,'(A)') ' intlbfgs> dumped NREPCUT:'

   WRITE(LUNIT,'(12L5)') INTFROZEN(1:NATOMS)
   ! WRITE(*,'(A)') ' intlbfgs> dumped INTFROZEN'

   WRITE(LUNIT,'(I8)') NCONOFF
   IF (NCONOFF.GT.0) WRITE(LUNIT,'(12I8)') CONOFFLIST(1:NCONOFF)
   IF (NCONOFF.GT.0) WRITE(LUNIT,'(12L5)') CONOFFTRIED(1:NCONSTRAINT)
   ! WRITE(*,'(A)') ' intlbfgs> dumped NCONOFF and CONOFFLIST'

CLOSE(LUNIT)

END SUBROUTINE INTRWG















