
SUBROUTINE CONDOUBLE
USE KEY, ONLY : CONI, CONJ, CONDISTREF, INTCONMAX, CONIFIX, CONJFIX, CONDISTREFFIX, NCONGEOM, &
  &             CONCUT, CONCUTFIX, CONOFFLIST, CONOFFTRIED
IMPLICIT NONE
DOUBLE PRECISION, ALLOCATABLE :: CPTEMP(:)
INTEGER, ALLOCATABLE :: ICPTEMP(:)
LOGICAL, ALLOCATABLE :: LCPTEMP(:)

ALLOCATE(ICPTEMP(INTCONMAX))
ALLOCATE(CPTEMP(INTCONMAX))
ALLOCATE(LCPTEMP(INTCONMAX))
                
ICPTEMP(1:INTCONMAX)=CONI(1:INTCONMAX)
DEALLOCATE(CONI)
ALLOCATE(CONI(2*INTCONMAX))
CONI(1:INTCONMAX)=ICPTEMP(1:INTCONMAX)

IF (NCONGEOM.GE.2) THEN
   ICPTEMP(1:INTCONMAX)=CONIFIX(1:INTCONMAX)
   DEALLOCATE(CONIFIX)
   ALLOCATE(CONIFIX(2*INTCONMAX))
   CONIFIX(1:INTCONMAX)=ICPTEMP(1:INTCONMAX)
               
   ICPTEMP(1:INTCONMAX)=CONJFIX(1:INTCONMAX)
   DEALLOCATE(CONJFIX)
   ALLOCATE(CONJFIX(2*INTCONMAX))
   CONJFIX(1:INTCONMAX)=ICPTEMP(1:INTCONMAX)
               
   CPTEMP(1:INTCONMAX)=CONDISTREFFIX(1:INTCONMAX)
   DEALLOCATE(CONDISTREFFIX)
   ALLOCATE(CONDISTREFFIX(2*INTCONMAX))
   CONDISTREFFIX(1:INTCONMAX)=CPTEMP(1:INTCONMAX)
               
   CPTEMP(1:INTCONMAX)=CONCUTFIX(1:INTCONMAX)
   DEALLOCATE(CONCUTFIX)
   ALLOCATE(CONCUTFIX(2*INTCONMAX))
   CONCUTFIX(1:INTCONMAX)=CPTEMP(1:INTCONMAX)
ENDIF
               
ICPTEMP(1:INTCONMAX)=CONJ(1:INTCONMAX)
DEALLOCATE(CONJ)
ALLOCATE(CONJ(2*INTCONMAX))
CONJ(1:INTCONMAX)=ICPTEMP(1:INTCONMAX)
               
ICPTEMP(1:INTCONMAX)=CONOFFLIST(1:INTCONMAX)
DEALLOCATE(CONOFFLIST)
ALLOCATE(CONOFFLIST(2*INTCONMAX))
CONOFFLIST(1:INTCONMAX)=ICPTEMP(1:INTCONMAX)
               
LCPTEMP(1:INTCONMAX)=CONOFFTRIED(1:INTCONMAX)
DEALLOCATE(CONOFFTRIED)
ALLOCATE(CONOFFTRIED(2*INTCONMAX))
CONOFFTRIED(1:INTCONMAX)=LCPTEMP(1:INTCONMAX)
CONOFFTRIED(INTCONMAX+1:2*INTCONMAX)=.FALSE.
               
CPTEMP(1:INTCONMAX)=CONDISTREF(1:INTCONMAX)
DEALLOCATE(CONDISTREF)
ALLOCATE(CONDISTREF(2*INTCONMAX))
CONDISTREF(1:INTCONMAX)=CPTEMP(1:INTCONMAX)
               
CPTEMP(1:INTCONMAX)=CONCUT(1:INTCONMAX)
DEALLOCATE(CONCUT)
ALLOCATE(CONCUT(2*INTCONMAX))
CONCUT(1:INTCONMAX)=CPTEMP(1:INTCONMAX)

INTCONMAX=2*INTCONMAX
DEALLOCATE(CPTEMP)
DEALLOCATE(ICPTEMP)
DEALLOCATE(LCPTEMP)

END SUBROUTINE CONDOUBLE