SUBROUTINE REPDOUBLE
USE KEY, ONLY : NREPMAX, REPI, REPJ, REPCUT, NREPI, NREPJ, NREPCUT, NCONGEOM, REPIFIX, REPJFIX, REPCUTFIX
IMPLICIT NONE
INTEGER, ALLOCATABLE :: IREPTEMP(:)
DOUBLE PRECISION, ALLOCATABLE :: REPTEMP(:)

ALLOCATE(IREPTEMP(NREPMAX),REPTEMP(NREPMAX))

IF (NCONGEOM.GE.2) THEN
   IREPTEMP(1:NREPMAX)=REPIFIX(1:NREPMAX)
   DEALLOCATE(REPIFIX)
   ALLOCATE(REPIFIX(2*NREPMAX))
   REPIFIX(1:NREPMAX)=IREPTEMP(1:NREPMAX)
   IREPTEMP(1:NREPMAX)=REPJFIX(1:NREPMAX)
   DEALLOCATE(REPJFIX)
   ALLOCATE(REPJFIX(2*NREPMAX))
   REPJFIX(1:NREPMAX)=IREPTEMP(1:NREPMAX)
   REPTEMP(1:NREPMAX)=REPCUTFIX(1:NREPMAX)
   DEALLOCATE(REPCUTFIX)
   ALLOCATE(REPCUTFIX(2*NREPMAX))
   REPCUTFIX(1:NREPMAX)=REPTEMP(1:NREPMAX)
ENDIF

IREPTEMP(1:NREPMAX)=REPI(1:NREPMAX)
DEALLOCATE(REPI)
ALLOCATE(REPI(2*NREPMAX))
REPI(1:NREPMAX)=IREPTEMP(1:NREPMAX)
IREPTEMP(1:NREPMAX)=REPJ(1:NREPMAX)
DEALLOCATE(REPJ)
ALLOCATE(REPJ(2*NREPMAX))
REPJ(1:NREPMAX)=IREPTEMP(1:NREPMAX)
REPTEMP(1:NREPMAX)=REPCUT(1:NREPMAX)
DEALLOCATE(REPCUT)
ALLOCATE(REPCUT(2*NREPMAX))
REPCUT(1:NREPMAX)=REPTEMP(1:NREPMAX)

IREPTEMP(1:NREPMAX)=NREPI(1:NREPMAX)
DEALLOCATE(NREPI)
ALLOCATE(NREPI(2*NREPMAX))
NREPI(1:NREPMAX)=IREPTEMP(1:NREPMAX)
IREPTEMP(1:NREPMAX)=NREPJ(1:NREPMAX)
DEALLOCATE(NREPJ)
ALLOCATE(NREPJ(2*NREPMAX))
NREPJ(1:NREPMAX)=IREPTEMP(1:NREPMAX)
REPTEMP(1:NREPMAX)=NREPCUT(1:NREPMAX)
DEALLOCATE(NREPCUT)
ALLOCATE(NREPCUT(2*NREPMAX))
NREPCUT(1:NREPMAX)=REPTEMP(1:NREPMAX)

DEALLOCATE(IREPTEMP,REPTEMP)
NREPMAX=2*NREPMAX

END SUBROUTINE REPDOUBLE