SUBROUTINE NMDALIGN(XYZ,NACTIVE,TURNONORDER,NITERDONE)
USE KEY, ONLY : INTIMAGE, TWOD, RIGIDBODY, BULKT
USE COMMONS, ONLY: NATOMS, DEBUG
IMPLICIT NONE                
INTEGER J5,J3,J4,J2,NACTIVE,NITERDONE
DOUBLE PRECISION XYZ((3*NATOMS)*(INTIMAGE+2)),COORDSA(3*NATOMS), COORDSB(3*NATOMS)
DOUBLE PRECISION DIST, DWORST, RMAT(3,3)
CHARACTER(LEN=5) ZUSE
INTEGER TURNONORDER(NATOMS)
INTEGER LUNIT, GETUNIT, LUNIT2
CHARACTER(LEN=80) :: FNAME

IF (DEBUG) PRINT *,'Doing NMD alignment for images NOW with NACTIVE=',NACTIVE
ZUSE='LA   '
WRITE(FNAME,'(I10)') NITERDONE
FNAME='active.' // TRIM(ADJUSTL(FNAME)) // '.xyz'
LUNIT=GETUNIT()
OPEN(LUNIT,FILE=TRIM(ADJUSTL(FNAME)))

    WRITE(LUNIT,'(I6)') NACTIVE
    WRITE(LUNIT,'(A,I6,A)') 'Image ',1,' before'
    DO J4=1,NACTIVE
       J2=TURNONORDER(J4)
       WRITE(LUNIT,'(A,3G20.10)') 'LA ',XYZ(3*(J2-1)+1:3*(J2-1)+3)
    ENDDO

WRITE(FNAME,'(I10)') NITERDONE
FNAME='activeNMD.' // TRIM(ADJUSTL(FNAME)) // '.xyz'
LUNIT2=GETUNIT()
OPEN(LUNIT2,FILE=TRIM(ADJUSTL(FNAME)))

    WRITE(LUNIT2,'(I6)') NACTIVE
    WRITE(LUNIT2,'(A,I6,A)') 'Image ',1,' after unchanged'
    DO J4=1,NACTIVE
       J2=TURNONORDER(J4)
       WRITE(LUNIT2,'(A,3G20.10)') 'LA ',XYZ(3*(J2-1)+1:3*(J2-1)+3)
    ENDDO

DO J3=1,INTIMAGE+1 
    WRITE(LUNIT,'(I6)') NACTIVE
    WRITE(LUNIT,'(A,I6,A)') 'Image ',J3+1,' before'
    DO J4=1,NACTIVE
       J2=TURNONORDER(J4)
       COORDSA(3*(J4-1)+1:3*(J4-1)+3)=XYZ(3*NATOMS*(J3-1)+3*(J2-1)+1:3*NATOMS*(J3-1)+3*(J2-1)+3)
       COORDSB(3*(J4-1)+1:3*(J4-1)+3)=XYZ(3*NATOMS*(J3  )+3*(J2-1)+1:3*NATOMS*(J3  )+3*(J2-1)+3)
       WRITE(LUNIT,'(A,3G20.10)') 'LA ',XYZ(3*NATOMS*(J3  )+3*(J2-1)+1:3*NATOMS*(J3  )+3*(J2-1)+3)
    ENDDO
    CALL NEWMINDIST(COORDSA,COORDSB,NACTIVE,DIST,BULKT,TWOD,ZUSE,.FALSE.,RIGIDBODY,DEBUG,RMAT,DWORST)

    WRITE(LUNIT2,'(I6)') NACTIVE
    WRITE(LUNIT2,'(A,I6,A)') 'Image ',J3+1,' after'
    DO J4=1,NACTIVE
       J2=TURNONORDER(J4)
       WRITE(LUNIT2,'(A,3G20.10)') 'LA ',COORDSB(3*(J4-1)+1:3*(J4-1)+3)
    ENDDO
ENDDO

CLOSE(LUNIT)
CLOSE(LUNIT2)

 ! STOP

END SUBROUTINE NMDALIGN