SUBROUTINE WRITEPROFILE(NITER,EEE,INTIMAGE)
IMPLICIT NONE 
INTEGER,INTENT(IN) :: INTIMAGE, NITER
INTEGER :: I,LUNIT,GETUNIT
DOUBLE PRECISION :: EEE(INTIMAGE+2)
CHARACTER(LEN=20) :: FILENAME

LUNIT=GETUNIT()
   
   FILENAME='int.EofS'

OPEN(UNIT=LUNIT,FILE=FILENAME,STATUS='replace')

WRITE(UNIT=LUNIT,FMT='(2g24.13)') EEE(1)
DO I=2,INTIMAGE+1
   WRITE(UNIT=LUNIT,FMT='(2G24.13)') EEE(I)
ENDDO
WRITE(UNIT=LUNIT,FMT='(2G24.13)') EEE(INTIMAGE+2)

CLOSE(LUNIT)
WRITE(*,'(A)') ' writeprofile> Interpolated energy profile was saved to file "'//trim(filename)//'"'

END SUBROUTINE WRITEPROFILE