!! This modules saves energies calculated by congrad for wiritng output

MODULE OUT_PRINT

    USE QCIPREC
    IMPLICIT NONE

    REAL(KIND = REAL64) :: SAVEECON, SAVEEREP, SAVEESPR, SAVEEDIH  
    REAL(KIND = REAL64) :: SAVEETOTAL                    ! overall energy
    REAL(KIND = REAL64) :: SAVERMS  
    REAL(KIND = REAL64) :: SAVEFCONTEST, SAVEFREPTEST
    REAL(KIND = REAL64) :: SAVECONVERGECONTEST, SAVECONVERGEREPTEST

    CONTAINS
    
    SUBROUTINE SAVE_OUT(ETOTAL, RMS, EREP, ECON, ESPR, EDIH, FCONTEST, FREPTEST, CONVERGECONTEST, CONVERGEREPTEST)
        IMPLICIT NONE
        
        REAL(KIND = REAL64), INTENT(IN) :: ETOTAL  
        REAL(KIND = REAL64), INTENT(IN) :: EREP, ECON, ESPR, EDIH
        REAL(KIND = REAL64), INTENT(IN) :: FCONTEST, FREPTEST, CONVERGECONTEST, CONVERGEREPTEST
        REAL(KIND = REAL64), INTENT(IN) :: RMS                       ! total force
        
        SAVEETOTAL = ETOTAL
        SAVEECON = ECON
        SAVEEREP = EREP
        SAVEEDIH = EDIH
        SAVEESPR  = ESPR

        SAVERMS = RMS

        SAVEFCONTEST = FCONTEST
        SAVEFREPTEST = FREPTEST
        SAVECONVERGECONTEST = CONVERGECONTEST
        SAVECONVERGEREPTEST = CONVERGEREPTEST

    END SUBROUTINE SAVE_OUT

    SUBROUTINE WRITE_CONGRADOUT()
        IMPLICIT NONE

         WRITE(*,*) " congrad> E total: ", SAVEETOTAL, "RMS: ", SAVERMS, " E rep: ", SAVEEREP, " E constr: ", SAVEECON
         WRITE(*,*) "                                              E spring: ", SAVEESPR, " E dih: ", SAVEEDIH
         WRITE(*,*) " congrad> FCONTEST: ", SAVEFCONTEST, " FREPTEST: ", SAVEFREPTEST
         WRITE(*,*) " congrad> CONVERGECONTEST: ", SAVECONVERGECONTEST, " CONVERGEREPTEST: ", SAVECONVERGEREPTEST
    END SUBROUTINE WRITE_CONGRADOUT

END MODULE OUT_PRINT
