MODULE TIMER_MODULE
  IMPLICIT NONE
  PRIVATE
  PUBLIC :: TIMER_START, TIMER_STOP
  
  INTEGER :: CLOCK_START, CLOCK_RATE
  
CONTAINS
  
  SUBROUTINE TIMER_START()
    CALL SYSTEM_CLOCK(COUNT_RATE=CLOCK_RATE)
    CALL SYSTEM_CLOCK(COUNT=CLOCK_START)
  END SUBROUTINE TIMER_START
  
  SUBROUTINE TIMER_STOP()
    INTEGER :: CLOCK_END
    REAL :: ELAPSED_TIME
    INTEGER :: HOURS, MINUTES, SECONDS, REMAINDER
    
    CALL SYSTEM_CLOCK(COUNT=CLOCK_END)
    ELAPSED_TIME = REAL(CLOCK_END - CLOCK_START) / REAL(CLOCK_RATE)
    
    ! CONVERT TO HOURS, MINUTES, SECONDS
    HOURS = INT(ELAPSED_TIME) / 3600
    REMAINDER = INT(ELAPSED_TIME) - (HOURS * 3600)
    MINUTES = REMAINDER / 60
    SECONDS = REMAINDER - (MINUTES * 60)
    
    PRINT '(A, I0, A, I0, A, I0, A)', "Runtime: ", HOURS, "h ", &
          MINUTES, "m ", SECONDS, "s"
    
  END SUBROUTINE TIMER_STOP
  
END MODULE TIMER_MODULE
