!! This modules saves energies calculated by congrad for wiritng output

MODULE OUT_PRINT

    USE QCIPREC
    IMPLICIT NONE

    REAL(KIND = REAL64) :: SAVEECON, SAVEEREP, SAVEESPR, SAVEEDIH  
    REAL(KIND = REAL64) :: SAVEETOTAL                    ! overall energy
    REAL(KIND = REAL64) :: SAVERMS  
    REAL(KIND = REAL64) :: SAVEFCONTEST, SAVEFREPTEST, SAVEFDIHTEST
    REAL(KIND = REAL64) :: SAVECONVERGECONTEST, SAVECONVERGEREPTEST, SAVEEDIHTEST

    CONTAINS
    
    SUBROUTINE SAVE_OUT(ETOTAL, RMS, EREP, ECON, ESPR, EDIH, FCONTEST, FREPTEST, FDIHTEST, CONVERGECONTEST, CONVERGEREPTEST, CONVERGENCEDIHTEST)
        IMPLICIT NONE
        
        REAL(KIND = REAL64), INTENT(IN) :: ETOTAL  
        REAL(KIND = REAL64), INTENT(IN) :: EREP, ECON, ESPR, EDIH
        REAL(KIND = REAL64), INTENT(IN) :: FCONTEST, FREPTEST, FDIHTEST
        REAL(KIND = REAL64), INTENT(IN) :: CONVERGECONTEST, CONVERGEREPTEST, CONVERGENCEDIHTEST
        REAL(KIND = REAL64), INTENT(IN) :: RMS                       ! total force
        
        SAVEETOTAL = ETOTAL
        SAVEECON = ECON
        SAVEEREP = EREP
        SAVEEDIH = EDIH
        SAVEESPR  = ESPR

        SAVERMS = RMS

        SAVEFCONTEST = FCONTEST
        SAVEFREPTEST = FREPTEST
        SAVEFDIHTEST = FDIHTEST
        SAVECONVERGECONTEST = CONVERGECONTEST
        SAVECONVERGEREPTEST = CONVERGEREPTEST
        SAVEEDIHTEST = CONVERGENCEDIHTEST

    END SUBROUTINE SAVE_OUT

    SUBROUTINE WRITE_CONGRADOUT()
        IMPLICIT NONE
         WRITE(*,*) " congrad> E total: ", SAVEETOTAL, "RMS: ", SAVERMS, " E rep: ", SAVEEREP, " E constr: ", SAVEECON
         WRITE(*,*) "                                              E spring: ", SAVEESPR, " E dih: ", SAVEEDIH
         WRITE(*,*) " congrad> FCONMAX: ", SAVEFCONTEST, " FREPMAX: ", SAVEFREPTEST, " FDIHMAX: ", SAVEFDIHTEST
         WRITE(*,*) " congrad> CONVERGECONTEST: ", SAVECONVERGECONTEST, " CONVERGEREPTEST: ", SAVECONVERGEREPTEST, " CONVERGEDIHTEST: ", SAVEEDIHTEST
    END SUBROUTINE WRITE_CONGRADOUT

END MODULE OUT_PRINT
