MODULE MOD_TERMINATE

   CONTAINS

      SUBROUTINE FINISH_QCI()
         USE INTERPOLATION_KEYS, ONLY: DEALLOC_INTERPOLATIONS_VARS
         USE CHIRALITY, ONLY: DEALLOC_CHIR_INTERNALS
         USE CONGEOM, ONLY: DEALLOC_CONGEOM
         USE QCICONSTRAINTS, ONLY: DEALLOC_CONSTR
         USE MOD_FREEZE, ONLY: DEALLOC_FREEZE
         USE MOD_INTCOORDS, ONLY: DEALLOC_INTCOORDS
         USE QCI_LINEAR, ONLY: DEALLOC_QCI_LINEAR
         USE REPULSION, ONLY: DEALLOC_REP_VARS
         USE ADDATOM, ONLY: DEALLOC_ADDATOM

         IMPLICIT NONE
         CALL DEALLOC_INTERPOLATIONS_VARS()
         CALL DEALLOC_CHIR_INTERNALS()
         CALL DEALLOC_CONGEOM()
         CALL DEALLOC_CONSTR()
         CALL DEALLOC_FREEZE()
         CALL DEALLOC_INTCOORDS()
         CALL DEALLOC_QCI_LINEAR()
         CALL DEALLOC_REP_VARS()
         CALL DEALLOC_ADDATOM()

      END SUBROUTINE FINISH_QCI


      SUBROUTINE INT_ERR_TERMINATE()
         IMPLICIT NONE

         WRITE(*,*) " terminateQCI> An error was encountered - QCI is terminated"
         WRITE(*,*) " terminateQCI> Deallocating variables"
         CALL FINISH_QCI()
         STOP

      END SUBROUTINE INT_ERR_TEMRINATE




END MODULE MOD_TERMINATE
