MODULE QCI_CONSTRAINT_KEYS
    USE QCIPREC
    IMPLICIT NONE
    INTEGER :: NCONSTRAINT = 0
    INTEGER, ALLOCATABLE :: CONI(:), CONJ(:), CONION(:), CONJON(:)
    REAL(KIND = REAL64), ALLOCATABLE :: CONDISTREF(:)
    REAL(KIND = REAL64), ALLOCATABLE :: CONCUT(:)
    INTEGER, ALLOCATABLE :: NCONPERATOM(:), CONLIST(:,:)
    INTEGER :: MAXCONSTRAINTS
 END MODULE QCI_CONSTRAINT_KEYS
 