MODULE QCI_CONSTRAINT_KEYS
   USE QCIPREC
   IMPLICIT NONE
   !constraint
   INTEGER :: MAXCONUSE = 100
   INTEGER :: QCICONSEP = 15
   REAL(KIND=REAL64) :: QCICONSTRAINTTOL = 0.1D0
   REAL(KIND=REAL64) :: QCICONCUT = 6.0D0   

   CHARACTER(LEN=30) :: GEOMFILE = "congeom.dat"
   INTEGER :: NCONGEOM = 0
   REAL(KIND=REAL64), ALLOCATABLE :: CONGEOM(:,:) 
   CHARACTER(LEN=30) :: CONSTRFILE = "constraintfile"

   INTEGER :: NCONSTRAINT = 0
   INTEGER, ALLOCATABLE :: CONI(:), CONJ(:), CONION(:), CONJON(:)
   REAL(KIND = REAL64), ALLOCATABLE :: CONDISTREF(:), CONDISTREFLOCAL(:)
   REAL(KIND = REAL64), ALLOCATABLE :: CONCUT(:), CONCUTLOCAL(:)
   INTEGER, ALLOCATABLE :: NCONPERATOM(:), CONLIST(:,:)
   INTEGER :: MAXCONSTRAINTS

   LOGICAL :: CONCUTABST = .FALSE.
   LOGICAL :: CONCUTFRACT = .FALSE.

   !cut off for constraints
   LOGICAL :: CONCUTABSINC = .FALSE.
   REAL(KIND=REAL64) :: CONCUTABS = 0.7D0
   REAL(KIND=REAL64) :: CONCUTABS2 = 0.05D0

   REAL(KIND=REAL64) :: CONCUTFRAC=0.1D0

 END MODULE QCI_CONSTRAINT_KEYS
 