MODULE INTERPOLATION_KEYS
   USE QCIPREC
   IMPLICIT NONE
   INTEGER :: DIMS
   REAL(KIND = REAL64), ALLOCATABLE :: XSTART(:), XFINAL(:)
   REAL(KIND = REAL64), ALLOCATABLE, TARGET :: XYZ(:), GGG(:)
   REAL(KIND = REAL64), ALLOCATABLE :: EEE(:)
   REAL(KIND = REAL64), POINTER :: X(:), G(:)
   REAL(KIND = REAL64) :: RMS

   INTEGER :: NCONSTRAINTON = 0
   LOGICAL, ALLOCATABLE :: CONACTIVE(:)
   INTEGER, ALLOCATABLE :: CONION(:), CONJON(:)
   INTEGER :: NACTIVE = 0
   LOGICAL, ALLOCATABLE :: ATOMACTIVE(:)
   INTEGER, ALLOCATABLE :: NTRIES(:), TURNONORDER(:)

   REAL(KIND = REAL64), ALLOCATABLE :: GTMP(:), DIAG(:), STP(:), SEARCHSTEP(:,:), GDIF(:,:), STEPIMAGE(:)
   
   CONTAINS

      SUBROUTINE ALLOC_INTCOORDS()
         USE QCIKEYS, ONLY: NATOMS, NIMAGES
         CALL DEALLOC_INTCOORDS()
         DIMS = (3*NATOMS)*NIMAGES
         ALLOCATE(XYZ((3*NATOMS)*(NIMAGES+2)))
         ALLOCATE(GGG((3*NATOMS)*(NIMAGES+2)))
         ALLOCATE(EEE(NIMAGES+2))
         X=>XYZ((3*NATOMS)+1:(3*NATOMS)*(NIMAGES+1))
         G=>GGG((3*NATOMS)+1:(3*NATOMS)*(NIMAGES+1))
      END SUBROUTINE ALLOC_INTCOORDS

      SUBROUTINE DEALLOC_INTCOORDS()
         X => NULL()
         G => NULL()
         IF (ALLOCATED(XYZ)) DEALLOCATE(XYZ)
         IF (ALLOCATED(GGG)) DEALLOCATE(GGG)
         IF (ALLOCATED(EEE)) DEALLOCATE(EEE)
      END SUBROUTINE DEALLOC_INTCOORDS


      SUBROUTINE ALLOC_INTERPOLATION_VARS()
         USE QCIKEYS, ONLY: NATOMS
         USE QCI_CONSTRAINT_KEYS, ONLY: NCONSTRAINT
         CALL DEALLOC_INTERPOLATION_VARS()
         !variables for active constraints
         ALLOCATE(CONACTIVE(NCONSTRAINT))
         ALLOCATE(CONION(NCONSTRAINT),CONJON(NCONSTRAINT))
         !variables for active atoms
         ALLOCATE(ATOMACTIVE(NATOMS))
         ALLOCATE(NTRIES(NATOMS))
         ALLOCATE(TURNONORDER(NATOMS))   
      END SUBROUTINE ALLOC_INTERPOLATION_VARS

      SUBROUTINE DEALLOC_INTERPOLATION_VARS()
         IF (ALLOCATED(CONACTIVE)) DEALLOCATE(CONACTIVE)
         IF (ALLOCATED(CONION)) DEALLOCATE(CONION)
         IF (ALLOCATED(CONJON)) DEALLOCATE(CONJON)
         IF (ALLOCATED(ATOMACTIVE)) DEALLOCATE(ATOMACTIVE)
         IF (ALLOCATED(NTRIES)) DEALLOCATE(NTRIES)
         IF (ALLOCATED(TURNONORDER)) DEALLOCATE(TURNONORDER)
      END SUBROUTINE DEALLOC_INTERPOLATION_VARS
      
      SUBROUTINE ALLOC_STEPTAKING()
         USE QCIKEYS, ONLY: NIMAGES, NATOMS,MUPDATE
         IMPLICIT NONE
         CALL DEALLOC_STEPTAKING()
         ALLOCATE(DIAG(3*NATOMS*NIMAGES))
         ALLOCATE(GTMP(3*NATOMS*NIMAGES))
         ALLOCATE(GDIF(0:MUPDATE,(3*NATOMS)*NIMAGES))
         ALLOCATE(STP(3*NATOMS*NIMAGES))
         ALLOCATE(SEARCHSTEP(0:MUPDATE,(3*NATOMS)*NIMAGES))
         ALLOCATE(STEPIMAGE(NIMAGES))
         DIAG = 0.0D0
         GTMP  = 0.0D00
         GDIF = 0.0D0
         STP = 0.0D0
         SEARCHSTEP = 0.0D0
         STEPIMAGE = 0.0D0
      END SUBROUTINE ALLOC_STEPTAKING

      SUBROUTINE DEALLOC_STEPTAKING()
         IF (ALLOCATED(DIAG)) DEALLOCATE(DIAG)
         IF (ALLOCATED(GTMP)) DEALLOCATE(GTMP)
         IF (ALLOCATED(GDIF)) DEALLOCATE(GDIF)
         IF (ALLOCATED(STP)) DEALLOCATE(STP)
         IF (ALLOCATED(SEARCHSTEP)) DEALLOCATE(SEARCHSTEP)
         IF (ALLOCATED(STEPIMAGE)) DEALLOCATE(STEPIMAGE)
      END SUBROUTINE DEALLOC_STEPTAKING
END MODULE INTERPOLATION_KEYS