MODULE INTERPOLATION_KEYS
   USE QCI_PREC
   IMPLICIT NONE
   INTEGER :: NCONSTRAINTON = 0
   LOGICAL, ALLOCATABLE :: CONACTIVE(:)
   INTEGER, ALLOCATABLE :: CONION(:), CONJON(:)
   INTEGER :: NACTIVE = 0
   LOGICAL, ALLOCATABLE :: ATOMACTIVE(:)
   INTEGER :: NTRIES(:), TURNONORDER(:)

   CONTAINS

      SUBROUTINE ALLOC_INTERPOLATION_VARS()
         USE QCI_KEYS, ONLY: NATOMS
         USE CONSTRAINTS, ONLY: NCONSTRAINT
         CALL DEALLOC_INTERPOLATION_VARS()
         !variables for active constraints
         ALLOCATE(CONACTIVE(NCONSTRAINT))
         ALLOCATE(CONION(NCONSTRAINT),CONJON(NCONSTRAINT))
         !variables for active atoms
         ALLOCATE(ATOMACTIVE(NATOMS))
         ALLOCATE(NTRIES(NATOMS))
         ALLOCATE(TURNONORDER(NATOMS))   

      END SUBROUTINE ALLOC_INTERPOLATION_VARS

      SUBROUTINE DEALLOC_INTERPOLATION_VARS()
         IF (ALLOCATED(CONACTIVE)) DEALLOCATE(CONACTIVE)
         IF (ALLOCATED(CONION)) DEALLOCATE(CONION)
         IF (ALLOCATED(CONJON)) DEALLOCATE(CONJON)
         IF (ALLOCATED(ATOMACTIVE)) DEALLOCATE(ATOMACTIVE)
         IF (ALLOCATED(NTRIES)) DEALLOCATE(NTRIES)
         IF (ALLOCATED(TURNONORDER)) DEALLOCATE(TURNONORDER)
      END SUBROUTINE DEALLOC_INTERPOLATION_VARS
END MODULE INTERPOLATION_KEYS