MODULE QCICONSTRAINTS
   USE QCIPREC
   IMPLICIT NONE

   CONTAINS
      ! create constraints
      SUBROUTINE CREATE_CONSTRAINTS()
         
      END SUBROUTINE CREATE_CONSTRAINTS

      ! from AMBER
      SUBROUTINE AMBER_QCI_CONSTRAINTS()

      END SUBROUTINE AMBER_QCI_CONSTRAINTS

      ! from HiRE
      SUBROUTINE HIRE_QCI_CONSTRAINTS()

      END SUBROUTINE HIRE_QCI_CONSTRAINTS





      ! create constraints from endpoints
      SUBROUTINE CREATE_FROM_ENDPOINTS()

      END SUBROUTINE CREATE_FROM_ENDPOINTS

      ! create constraints from input geometries
      SUBROUTINE CREATE_FROM_GEOMETRIES()

      END SUBROUTINE CREATE_FROM_GEOMETRIES
      
      ! add constraints list
      SUBROUTINE ADD_CONSTRAINT_LIST()

      END SUBROUTINE ADD_CONSTRAINT_LIST


END MODULE QCICONSTRAINTS