MODULE QCI_LINEAR
   USE QCIPREC
   IMPLICIT NONE
   ! number of atoms for QCIlinear
   INTEGER :: NQCILINEAR = 0
   ! cutoff for QCIlinear treatment
   REAL(KIND=REAL64) :: LINEARCUT = 0.5D0
   ! list of linear atoms
   INTEGER, ALLOCATABLE :: LINEARATOMS(:)
   ! file name linear atoms
   CHARACTER(25) :: LINEARFILE = "QCIlinear"

   CONTAINS

      SUBROUTINE GET_LINEAR_ATOMS()
         USE QCIKEYS, ONLY: NATOMS
         USE QCIFILEHANDLER, ONLY: FILE_LENGTH, GETUNIT        
         USE MOD_INTCOORDS, ONLY: XSTART, XFINAL
         USE HELPER_FNCTS, ONLY: DISTANCE_ATOM_DIFF_IMAGES
         INTEGER :: NDUMMY, DUMMY
         INTEGER :: LINEART(NATOMS)
         REAL(KIND=REAL64) :: DIST
         INTEGER :: J1
         INTEGER :: LINUNIT
         LOGICAL :: YESNO

         LINEART(1:NATOMS) = 0
         INQUIRE(FILE=LINEARFILE, EXIST=YESNO)
         IF (YESNO) THEN
            WRITE(*,*) " get_linear_atoms> Reading in linear atoms from file"
            LINUNIT = GETUNIT()
            OPEN(LINUNIT,FILE=LINEARFILE,STATUS='OLD')
            READ(LINUNIT, '(I6)') NDUMMY
            DO J1=1,NDUMMY
               READ(LINUNIT, '(I6)') DUMMY
               LINEARLIST(DUMMY) = 1
            END DO
            CLOSE(LINUNIT)
         END IF

         DO J1=1,NATOMS
            CALL DISTANCE_ATOM_DIFF_IMAGES(NATOMS, XSTART, XFINAL, J1, DIST)
            IF (DIST.LT.LINEARCUT) THEN
               LINEARLIST(J1) = 1
            END IF
         END DO

         NQCILINEAR = SUM(LINEARLIST)
         CALL ALLOC_QCI_LINEAR()
         DUMMY=0
         DO J1=1,NATOMS
            IF (LINEART(J1).EQ.1) THEN
               DUMMY = DUMMY + 1
               LINEARATOMS(DUMMY) = J1
            END IF
         END DO
      END SUBROUTINE GET_LINEAR_ATOMS
   
      SUBROUTINE ALLOC_QCI_LINEAR()
         CALL DEALLOC_QCI_LINEAR
         ALLOCATE(LINEARATOMS(NQCILINEAR))
      END SUBROUTINE ALLOC_QCI_LINEAR

      SUBROUTINE DEALLOC_QCI_LINEAR()
         IF (ALLOCATED(LINEARATOMS)) DEALLOCATE(LINEARATOMS)
      END SUBROUTINE DEALLOC_QCI_LINEAR

END MODULE QCI_LINEAR