MODULE MOD_INTCOORDS
   USE QCIPREC
   USE QCIKEYS, ONLY: NATOMS, NIMAGES
   IMPLICIT NONE 
   REAL(KIND = REAL64), ALLOCATABLE :: XSTART(:), XFINAL(:)
   REAL(KIND = REAL64), ALLOCATABLE :: XYZ(:), GGG(:), EEE(:)
   REAL(KIND = REAL64), POINTER :: X(:), G(:)

   INTEGER :: NCONLARGEST, NCONSMALLEST
   REAL(KIND = REAL64) :: DCONLARGEST, DCONSMALLEST
   CONTAINS

      SUBROUTINE ALLOC_INTCOORDS()
         CALL DEALLOC_INTCOORDS()
         ALLOCATE(XYZ((3*NATOMS)*(NIMAGES+2)))
         ALLOCATE(GGG((3*NATOMS)*(NIMAGES+2)))
         ALLOCATE(EEE(NIMAGES+2))
         X=>XYZ((3*NATOMS)+1:(3*NATOMS)*(NIMAGES+1))
         G=>GGG((3*NATOMS)+1:(3*NATOMS)*(NIMAGES+1))
      END SUBROUTINE ALLOC_INTCOORDS

      SUBROUTINE DEALLOC_INTCOORDS()
         X => NULL()
         G => NULL()
         IF (ALLOCATED(XYZ)) DEALLOCATE(XYZ)
         IF (ALLOCATED(GGG)) DEALLOCATE(GGG)
         IF (ALLOCATED(EEE)) DEALLOCATE(EEE)
      END SUBROUTINE DEALLOC_INTCOORDS

      SUBROUTINE SETUP_ENDPOINTS(NATS)
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: NATS
         NATOMS = NATS
         ALLOCATE(XSTART(3*NATOMS),XFINAL(3*NATOMS))
      END SUBROUTINE SETUP_ENDPOINTS

      SUBROUTINE INITIATE_INTERPOLATION_BAND(DEBUG)
         USE QCIFILEHANDLER, ONLY: GETUNIT
         USE QCIKEYS, ONLY: QCIFROZEN, NCQIFROZEN
         IMPLICIT NONE
         LOGICAL, INTENT(IN) :: DEBUG
         INTEGER :: J1, J2, J3, LUNIT

         CALL ALLOC_INTCOORDS()
         XYZ(1:(3*NATOMS))=QSTART(1:(3*NATOMS))
         XYZ((3*NATOMS)*(NIMAGES+1)+1:(3*NATOMS)*(NIMAGES+2))=QFINISH(1:(3*NATOMS))
         DO J1=1,NIMAGES+2
            XYZ((J1-1)*(3*NATOMS)+1:J1*(3*NATOMS))=((NIMAGES+2-J1)*QSTART(1:(3*NATOMS))+(J1-1)*QFINISH(1:(3*NATOMS)))/(NIMAGES+1)
         ENDDO

         !Deal with any frozen atoms
         IF (NQCIFROZEN.GT.0) THEN
            DO J1=1,NATOMS
               IF (QCIFROZEN(J1)) THEN
                  ATOMACTIVE(J1)=.TRUE.
                  NACTIVE=NACTIVE+1
                  TURNONORDER(NACTIVE)=J1
                  NTRIES(J1)=1
               END IF
            END DO
         END IF

         IF (DEBUG) THEN
            LUNIT=GETUNIT()
            OPEN(UNIT=LUNIT,FILE='linear.xyz',STATUS='replace')
            DO J2=1,NIMAGES+2
               WRITE(LUNIT,'(I6)') NATOMS
               DO J3=1,NATOMS
                     WRITE(LUNIT,'(A5,1X,3F20.10)') 'LA   ', XYZ((J2-1)*3*NATOMS+3*(J3-1)+1),  &
                                  XYZ((J2-1)*3*NATOMS+3*(J3-1)+2), XYZ((J2-1)*3*NATOMS+3*(J3-1)+3)
               ENDDO
            ENDDO
            CLOSE(LUNIT)
         END IF
      END SUBROUTINE INITIATE_INTERPOLATION_BAND

      SUBROUTINE GET_DISTANCES_CONSTRAINTS(NBEST)
         USE QCIKEYS, ONLY: QCIDOBACK, ISBBATOM
         USE QCICONSTRAINTS, ONLY: NCONSTRAINT
         USE HELPER_FNCTS, ONLY: DISTANCE_ATOM_DIFF_IMAGES
         IMPLICIT NONE
         INTEGER, INTENT(OUT) :: NBEST
         INTEGER :: J1, BACKBEST
         REAL(KIND = REAL64) :: DF, D1, D2, CURRLARGEST, CURRSMALLEST, CURRBBDIST

         BACKBEST = -1
         CURRLARGEST = -1.0D100
         CURRSMALLEST = 1.0D100
         CURRBBDIST = 1.0D100

         DO J1=1,NCONSTRAINT
            IF (QCIDOBACK.AND.(.NOT.ISBBATOM(CONI(J1)).OR.(.NOT.ISBBATOM(CONJ(J1))))) CYCLE
            ! we want to collect the change in atom positions between the endpoints
            CALL DISTANCE_ATOM_DIFF_IMAGES(NATOMS, QSTART, QFINAL, CONI(J1), D1)
            CALL DISTANCE_ATOM_DIFF_IMAGES(NATOMS, QSTART, QFINAL, CONJ(J1), D2)
            DF = D1 + D2
            IF (DF.LT.CURRSMALLEST) THEN
               CURRSMALLEST = DF
               NCONSMALLEST = J1
            END IF
            IF (DF.LT.CURRBBDIST) THEN
               IF (QCIDOBACK.AND.(ISBBATOM(CONI(J1))).AND.(ISBBATOM(CONJ(J1)))) THEN
                  CURRBBDIST = DF
                  BACKBEST = J1
               END IF
            END IF
            IF (DF.GT.CURRLARGEST) THEN
               CURRLARGEST = DF
               NCONLARGEST = J1
            END IF
         END DO
         IF (QCIDOBACK.AND.(BACKBEST.GT.0)) THEN
            NCONSMALLEST=BACKBEST  ! ensures NBEST is set if there are frozen atoms and DOBACK is set 
         END IF
         NBEST = NCONSMALLEST
      END SUBROUTINE GET_DISTANCES_CONSTRAINTS
END MODULE MOD_INTCOORDS