MODULE REPULSION
   USE QCIPREC
   USE QCI_KEYS
   IMPLICIT NONE
   INTEGER :: NREPCURR = 0
   INTEGER, ALLOCATABLE :: REPI(:), REPJ(:)
   INTEGER, ALLOCATABLE :: NREPI(:), NREPJ(:) 
   REAL(KIND = REAL64), ALLOCATABLE :: REPCUT, NREPCUT
   REAL(KIND = REAL64) :: CHECKREPCUTOFF
   INTEGER :: NNREPULSIVE, NREPULSIVE
   CONTAINS
      SUBROUTINE ALLOC_REP_VARS(NSIZE)
         CALL DEALLOC_REP_VARS()
         ALLOCATE(REPI(NSIZE), REPJ(NSIZE), NREPI(NSIZE), NREPJ(NSIZE),
                  REPCUT(NSIZE), NREPCUT(NSIZE))
      END SUBROUTINE ALLOC_REP_VARS


      SUBROUTINE DEALLOC_REP_VARS()
         IF (ALLOCATED(REPI)) DEALLOCATE(REPI)
         IF (ALLOCATED(REPJ)) DEALLOCATE(REPJ)
         IF (ALLOCATED(NREPI)) DEALLOCATE(NREPI)
         IF (ALLOCATED(NREPJ)) DEALLOCATE(NREPJ)
         IF (ALLOCATED(REPCUT)) DEALLOCATE(REPCUT)
         IF (ALLOCATED(NREPCUT)) DEALLOCATE(NREPCUT)        
      END SUBROUTINE DEALLOC_REP_VARS


      SUBROUTINE DOUBLE_REP_ARRAYS()

      END SUBROUTINE DOUBLE_REP_ARRAYS

      SUBROUTINE CHECKREP(XYZ, NSTART, NNSTART)
         USE QCI_KEYS, ONLY: NATOMS, NIMAGE
         USE HELPER_FNCTS, ONLY: DISTANCE_TWOATOMS
         IMPLICIT NONE
         REAL(KIND = REAL64), INTENT(IN) :: XYZ(3*NATOMS*(NIMAGE+2))
         INTEGER, INTENT(IN) :: NSTART, NNSTART
         INTEGER :: J, K, NI, NJ
         REAL(KIND = REAL64) :: COMPARE, LDIST


         ! QUERY: what is this assignment? Why soi it correct - need to understand structure
         NNREPULSIVE = NNSTART

         ! loop over part of the repulsion list
         DO J = NSTART, NREPULSIVE
            COMPARE = (CHECKREPCUTOFF*REPCUT(J))**2
            NI = REPI(J)
            NJ = REPJ(J)
            ! now check for the distance between atoms in all images
            DO K=1,NIMAGE+2
               CALL DISTANCE_TWOATOMS(NATOMS, XYZ((K-1)*3*NATOMS+1:3*K*NATOMS) , NI, NJ, LDIST)
               IF (LDIST.LT.COMPARE) THEN
                  NNREPULSIVE = NNREPULSIVE + 1
                  NREPI(NNREPULSIVE) = NI
                  NREPJ(NNREPULSIVE) = NJ
                  NREPCUT(NNREPULSIVE) = REPCUT(J)
                  EXIT
               END IF
            END DO
         END DO

      END SUBROUTINE CHECKREP

END MODULE REPULSION