MODULE AMBER_CONSTRAINTS
   USE QCIPREC
   IMPLICIT NONE

   CONTAINS
      ! from AMBER
      SUBROUTINE AMBER_QCI_CONSTRAINTS()

      END SUBROUTINE AMBER_QCI_CONSTRAINTS

END MODULE AMBER_CONSTRAINTS