MODULE QCI_INTERFACE
   INTEGER, PARAMETER  :: R64 = SELECTED_REAL_KIND(15, 307) 

   CONTAINS
      SUBROUTINE PASS_DATA(NATS, XS, XF)
         USE QCI_KEYS, ONLY: NATOMS, XSTART, XFINAL
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: NATS
         REAL(KIND = R64), INTENT(IN) :: XS(3*NATS), XF(3*NATS)

         NATOMS = NATS
         ALLOCATE(XSTART(3*NATOMS),XFINAL(3*NATOMS))
         XSTART(1:3*NATOMS) = XS(1:3*NATOMS)
         XFINAL(1:3*NATOMS) = XF(1:3*NATOMS)
      END SUBROUTINE PASS_DATA

END MODULE QCI_INTERFACE