MODULE QCI_INTERFACE
   INTEGER, PARAMETER  :: R64 = SELECTED_REAL_KIND(15, 307) 

   CONTAINS
      SUBROUTINE PASS_DATA(NATS, XS, XF)
         USE MOD_INTCOORDS, ONLY: SETUP_ENDPOINTS
         IMPLICIT NONE
         INTEGER, INTENT(IN) :: NATS
         REAL(KIND = R64), INTENT(IN) :: XS(3*NATS), XF(3*NATS)

         CALL SETUP_ENDPOINTS(NATS)
         XSTART(1:3*NATS) = XS(1:3*NATS)
         XFINAL(1:3*NATS) = XF(1:3*NATS)
      END SUBROUTINE PASS_DATA

      SUBROUTINE QCI_INITIALISE(PARAMFILE, ALIGNT)
         USE QCISETUP, ONLY: QCI_INIT
         IMPLICIT NONE
         CHARACTER(*), INTENT(IN) :: PARAMFILE
         LOGICAL, INTENT(IN) :: ALIGNT

         CALL QCI_INIT(PARAMFILE, ALIGNT)

      END SUBROUTINE QCI_INITIALISE

END MODULE QCI_INTERFACE